#server {
#    listen 80;
#    server_name localhost;
#    root /usr/share/nginx/html;
#    index index.html;

    # Proxy vers le backend Django
#    location /api/ {
#        proxy_pass http://orchestrateur:8000;
#        proxy_set_header Host $host;
#        proxy_set_header X-Real-IP $remote_addr;
#    }

    # Angular routing (SPA)
#    location / {
#        try_files $uri $uri/ /index.html;
#    }
#}


# frontend/nginx.conf
# Serveur nginx pour l'application Angular SPA.
# IMPORTANT : try_files avec fallback index.html pour que le routing
# Angular (chat, admin/fraud-rules, etc.) fonctionne sur refresh ou accès direct.

server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    large_client_header_buffers 4 32k;

    # Compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;

    # Assets statiques — cache long
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    # SPA fallback — TOUTES les routes retournent index.html
    # Angular Router gère ensuite le routing côté client
    location / {
        try_files $uri $uri/ /index.html;
    }
}