version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: bank_chat_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev
    restart: unless-stopped
