# Generated by Django 4.2.29 on 2026-04-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversation_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='archived_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
